generic4/urls.py
from django.contrib import admin
from django.urls import path
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.StudentListview.as_view(),name='home')
]

app/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name=models.CharField(max_length=30)
    roll=models.IntegerField()
    course=models.CharField(max_length=30)

app/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import Student
# Create your views here.
class StudentListview(ListView):
    model=Student
    # template_name_suffix='_list'
    #template_name_suffix if we want to change in ours default and make ours some things own custom
    #we also do ordering here
    ordering=['id']
    #if we want to give our own template instead of 
    #default template
    template_name='app/home.html'
    #we also use inbuilt method def __queryset
    #to return the query set filter the query set
    def get_queryset(self):
        return Student.objects.filter(id='2')
    #get_queryset will return the relevent filter amount of the data

app/templates/app/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>list view</title>
</head>
<body>
    <h1>hey every one this is the list view generic concept</h1>
    
    {% for student in student_list %}
        <hr>
        {{student.id}}<br>
        {{student.roll}}<br>
        {{student.name}}<br>
        {{student.course}}<br>
        <hr>
    
    {% endfor %}
        
</body>
</html>

app/templates/app/student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>list view</title>
</head>
<body>
    <h1>hey every one this is the list view generic concept</h1>
    
    {% for student in student_list %}
        <hr>
        {{student.id}}<br>
        {{student.roll}}<br>
        {{student.name}}<br>
        {{student.course}}<br>
        <hr>
    
    {% endfor %}
        
</body>
</html>